# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_chip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_Waveguide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField()),
                ('run_specifications', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('laser_source', models.CharField(blank=True, max_length=50)),
                ('readout', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Full_Name_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Wafer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Waveguide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.FloatField()),
                ('offset', models.FloatField()),
                ('frecuency', models.FloatField()),
                ('i_up', models.FloatField()),
                ('i_down', models.FloatField()),
                ('slope', models.FloatField()),
                ('visibility', models.FloatField()),
                ('noise', models.FloatField()),
                ('lod', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Run')),
                ('wafer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Wafer')),
                ('waveguide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Name_Waveguide')),
            ],
        ),
        migrations.DeleteModel(
            name='Chip',
        ),
    ]
