# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170831_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='date',
        ),
        migrations.RemoveField(
            model_name='run',
            name='laser_source',
        ),
        migrations.RemoveField(
            model_name='run',
            name='readout',
        ),
        migrations.RemoveField(
            model_name='run',
            name='user_name',
        ),
    ]
