# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170831_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('laser_source', models.CharField(blank=True, max_length=50)),
                ('readout', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Run')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Full_Name_Users')),
                ('wafer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Wafer')),
            ],
        ),
    ]
