# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_chip'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveguide',
            name='chip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Chip'),
        ),
    ]
