# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_waveguide_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='date',
            field=models.DateField(),
        ),
    ]
