# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170904_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveguide',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
