# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_waveguide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='molecular_weight',
            field=models.CharField(blank=True, help_text='Molecular weight of the chemical.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='concentration',
            field=models.CharField(blank=True, help_text='Concentration of the chemical.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the chemical.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='quantity',
            field=models.CharField(help_text='Quantity of the chemical.', max_length=20),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference of the chemical.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier of the chemical.', on_delete=django.db.models.deletion.CASCADE, to='blog.Supplier'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='type_chemical',
            field=models.ForeignKey(help_text='Type of the chemical.', on_delete=django.db.models.deletion.CASCADE, to='blog.Type_Chemical'),
        ),
        migrations.AlterField(
            model_name='computing',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the element was created.'),
        ),
        migrations.AlterField(
            model_name='computing',
            name='keyboard',
            field=models.CharField(blank=True, help_text='keyboard of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='location',
            field=models.ForeignKey(help_text='Where it is the computer.', on_delete=django.db.models.deletion.CASCADE, to='blog.Location'),
        ),
        migrations.AlterField(
            model_name='computing',
            name='memory',
            field=models.CharField(blank=True, help_text='How much memory have the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='model',
            field=models.CharField(blank=True, help_text='Model of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='mouse',
            field=models.CharField(blank=True, help_text='Mouse of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='others',
            field=models.CharField(blank=True, help_text='Others characteristics of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='processor',
            field=models.CharField(blank=True, help_text='Processor of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='screen_1',
            field=models.CharField(blank=True, help_text='Model of the screen of the computer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='screen_2',
            field=models.CharField(blank=True, help_text='Model of the second screen of the computer if this have a second screen.', max_length=200),
        ),
        migrations.AlterField(
            model_name='computing',
            name='setup',
            field=models.ForeignKey(blank=True, help_text='In order to the computer is used.', on_delete=django.db.models.deletion.CASCADE, to='blog.Setup'),
        ),
        migrations.AlterField(
            model_name='computing',
            name='type_object',
            field=models.ForeignKey(help_text='Type of the computing.', on_delete=django.db.models.deletion.CASCADE, to='blog.Type_Object'),
        ),
        migrations.AlterField(
            model_name='computing',
            name='user_name',
            field=models.ForeignKey(blank=True, help_text='Username of this computer.', on_delete=django.db.models.deletion.CASCADE, to='blog.Full_Name_Users'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='closet',
            field=models.ForeignKey(help_text='In what closet is the electronic component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Closet'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the element was created.'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='location',
            field=models.ForeignKey(help_text='Where it is the electronic component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Location'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='type_component',
            field=models.ForeignKey(help_text='Type of the electronic component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Type_Component'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='unit',
            field=models.ForeignKey(help_text='Unit of the value of the electronic componente.', on_delete=django.db.models.deletion.CASCADE, to='blog.Unit'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='value',
            field=models.CharField(blank=True, help_text='Value of the electronic component.', max_length=200),
        ),
        migrations.AlterField(
            model_name='element',
            name='author',
            field=models.ForeignKey(help_text='Name of the author that created the element.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='element',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the element was created.'),
        ),
        migrations.AlterField(
            model_name='element',
            name='maker',
            field=models.CharField(help_text='Manufacturer of the element.', max_length=200),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(help_text='Name of the element.', max_length=200),
        ),
        migrations.AlterField(
            model_name='element',
            name='type_item',
            field=models.ForeignKey(help_text='Type of element.', on_delete=django.db.models.deletion.CASCADE, to='blog.Type'),
        ),
    ]
