# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170918_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the optic component.', max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when was created.')),
                ('closet', models.ForeignKey(help_text='In what closet is the optic component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Closet')),
                ('location', models.ForeignKey(help_text='Where it is the optic component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Optic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the type of optic component.', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when was created.')),
            ],
        ),
        migrations.AddField(
            model_name='optic',
            name='type_optic',
            field=models.ForeignKey(help_text='Type of the optic component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Type_Optic'),
        ),
    ]
