# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170926_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='date',
            field=models.DateField(blank=True, help_text='When was took.', null=True),
        ),
    ]
