# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170926_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number_Closet',
        ),
        migrations.RemoveField(
            model_name='biological',
            name='closet',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='closet',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='closet',
        ),
        migrations.RemoveField(
            model_name='optic',
            name='closet',
        ),
        migrations.DeleteModel(
            name='Closet',
        ),
    ]
