# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20171107_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biological',
            old_name='unit_chemical',
            new_name='unit_biological',
        ),
    ]
