# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20171107_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biological',
            name='unit_biological',
            field=models.ForeignKey(help_text='Unit to the concentration/molecular weight of the biological.', on_delete=django.db.models.deletion.CASCADE, to='blog.Unit_Chemical'),
        ),
    ]
