# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_order_number_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='name_component',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
