# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_electronic_name_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='optic',
            name='name_optic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
