# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_optic_name_optic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Biological_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the type of biological component.', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when was created.')),
            ],
        ),
        migrations.RenameModel(
            old_name='Type_Biological',
            new_name='Type_Biological_1',
        ),
        migrations.AddField(
            model_name='type_biological_2',
            name='type_biological_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Type_Biological_1'),
        ),
    ]
