# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20171109_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biological',
            name='type_biological',
            field=models.ForeignKey(help_text='Type of the biological component.', on_delete=django.db.models.deletion.CASCADE, to='blog.Type_Biological_2'),
        ),
    ]
