# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20171109_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the state of chemical.', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when was created.')),
            ],
        ),
        migrations.AddField(
            model_name='type_chemical',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.State'),
        ),
    ]
