# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20171110_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_exists',
            field=models.BooleanField(default=False, help_text='To know if this order has a file assigned.'),
        ),
    ]
