# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_order_file_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_file_attach',
            field=models.CharField(blank=True, help_text='Name of the file upload.', max_length=200, null=True),
        ),
    ]
