# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_order_name_file_attach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the consumable.', max_length=200)),
                ('characteristics', models.CharField(blank=True, help_text='Important features of the consumable.', max_length=200)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer of the consumable.', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when was created.')),
                ('location', models.ForeignKey(help_text='Where it is the consumable.', on_delete=django.db.models.deletion.CASCADE, to='blog.Location')),
                ('supplier', models.ForeignKey(help_text='Seller of the consumable.', on_delete=django.db.models.deletion.CASCADE, to='blog.Supplier')),
            ],
        ),
    ]
