# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_consumable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='date',
            field=models.DateField(blank=True, help_text='MM/DD/YY', null=True),
        ),
    ]
